baseURL = 'https://ggtruss.github.io/Blog/'
languageCode = 'en-us'
title = 'Christian Trussler'
theme= "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5


[params]
	subtitle = "Creativity and Innovation"
	[params.author]
		name = "Christian Trussler"
		avatar = "/images/avatar.jpg"
		bio = "Christian Trussler is a Content Creator and Writer."
		email = "christiantrussler@hotmail.com"
	[params.image]
	  feature = "/images/homepage-1.png"